### ISSUE TITLE
Why app made with Magix Does not work on github pages ?

### ISSUE THREAD

**Issue by karanganesan** [etiennepinchon/magixjs#7]
https://karanganesan.github.io/magix/    ...

**Comment by etiennepinchon** [comment]
You are right, app made with magiX do not work with github pages. It is because magix require 2 server routes "/build" and "/documents" which are not delivered by github.
We need to fix that, I am going to code all night the new command "magix publish" so you will be able to publish your project right away.
Thanks for the reminder at this missing key element!
I keep you inform of the progress, this should not take too long ;)

**Comment by etiennepinchon** [comment]
I also need to add new command like "magix login" and "magix sync" to sync up your projects but anyway, after that we should be good!

**Comment by karanganesan** [comment]
Cool

**Comment by karanganesan** [comment]
Myself made a temporary fix for hosting on Github Pages

1. Made all files (all JS files) in the root folder ...
2. Change the location directory of index and catlog js in index.html
3.chage App.js directory in index.js

**Comment by karanganesan** [comment]
Myself made a temporary fix for hosting on Github Pages

1. Made all files (all JS files) in the root folder ...
2. Change the location directory of index and catlog js in index.html
3.chage App.js directory in index.js
